#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='mvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath manpath path
typeset -gUT INFOPATH infopath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that info searches for manuals.
infopath=(
  /usr/local/share/info
  /usr/share/info
  $infopath
)

# Set the list of directories that man searches for manuals.
manpath=(
  /usr/local/share/man
  /usr/share/man
  $manpath
)

for path_file in /etc/manpaths.d/*(.N); do
  manpath+=($(<$path_file))
done
unset path_file

# PETSc

# Set the list of directories that Zsh searches for programs.
path=(
  ~/bin
  /usr/local/share/python
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $PETSC_DIR/$PETSC_ARCH/bin
  /usr/local/Cellar/ruby/1.9.3-p194/bin
  $path
)

for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

#
# Temporary Files
#

if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi

alias pyserver="python -m SimpleHTTPServer"

alias mpirun="/Users/ketch/Research/Software/petsc/arch-darwin-c-debug/bin/mpirun"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
#export PETSC_DIR=/Users/ketch/Research/Software/petsc PETSC_ARCH=arch-darwin-c-debug

export SOFT=/Users/ketch/Research/Software
export PYTHONPATH=/Users/ketch/python:$SOFT
export PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
export PYTHONPATH=/Users/ketch/Research/Software/petsc/arch-darwin-c-debug/lib:$PYTHONPATH

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
